jobs:
  build:
    machine:
      image: ubuntu-2004:2023.04.2
    steps:
      - checkout
      # Whatever you want to do
      - run:
          name: Setup Tool
          command: |
            sudo apt-get install -y android-sdk-build-tools
            for apk_file in $(sudo find -type f -name *.apk) ; do
                package_name=$(sudo aapt2 dump badging $apk_file | grep package | head -1 | awk '{print $2}' | sed s/name=//g | sed s/\'//g  )
                if [[ $package_name = $1 ]]; then
                  echo $(basename $apk_file)	
                fi
              done